### ISSUE TITLE
Empty?

### ISSUE THREAD

**Issue by norcis** [erkanina/TdoaSimulator#1]
I find you project empty. Could you share your project?
I have five points (latitudes and longitudes) and time or distance. I need to find a point.

**Comment by erkanina** [comment]
Hello norcis,
Sorry for being late. I uploaded a simple working version. Not user friendly, but easy to understand tdoa math. In code there's some namings like "Trilateration". Dont consider them. They are copy/paste remnant of my previous trilateration project.
